name: Go Test

on:
  # Run tests on every push to any branch
  push:
    branches:
      - '**'
  # Run tests on pull requests that target the 'main' branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # Specify your Go version

      # Run Go tests
      - name: Run Go tests
        run: go test ./...

      # Ensure test failures cause the workflow to fail
      - name: Verify test results
        if: failure()
        run: echo "Tests failed!" && exit 1
